### ISSUE TITLE
vecxi on retina display

### ISSUE THREAD

**Issue by vodkaflip** [malbanGit/Vide#11]
On mac retina displays, vecxi only uses 1/4 of the window size (even when using shift-p). It would be nice to have a setting to expand this to use the full window...

**Comment by malbanGit** [comment]
There are some documentations on the net to fix this.

But I haven't access to a retina display, so I'm not confident I can fix this as long as I don't.
I'll put it only todo list.

**Comment by vodkaflip** [comment]
just found that by using the -oj+ flag, vexci uses the entire window! so no need to fix, unless support for 'java graphics' would disappear...

**Comment by malbanGit** [comment]
You can turn off JOGL usage in the config. If saved to the name "default" - this config will be loaded per default. So you do not need to use a parameter all the time.
