### ISSUE TITLE
How can I reset windows preferences?

### ISSUE THREAD

**Issue by AlexandreMinard** [malbanGit/Vide#13]
Hi,

Vide is so great, thanks for developing it!

I've several little issues with my windows inside Vide:
- I lost my "tracki" window and don't know how to get it back
- When I resize my vecxi window, the vectrex screen does not change its dimension. So I stay with a little screen. Too bad :(

In general, can I reset all window settings?

Thanks in advance for the answers.

Regards,
Alexandre

**Comment by malbanGit** [comment]
Hi!
a) most settings are stored in the Vide/serialize folder. You can delete the „*.ser“ files you wish to reset.
b) tracki is part of „dissi“, so it is invoked from the „dissi“ window (the button in „middle“ with the tooltip „show tracker“
c) per default vecxi keeps the aspect ration of the vectrex, so perhaps that is the reason, why the size does not change?
    If so - under configuration -> display „Fullscreen setup“, there is a checkbox „keep aspect ratio“, which is per default switched on

**Comment by AlexandreMinard** [comment]
Hi

Thanks for your (really quick) answer.

I got my tracki window back, thanks :)
For vecxi, the aspect ratio is okay, but the vectrex screen takes only 1/4 of the screen.
Here is a video so you can see that: https://streamable.com/zk2ee0

Regards,
Alexandre

**Comment by AlexandreMinard** [comment]
Even deleting all files in serialize folder didn't help

**Comment by malbanGit** [comment]
Hm.
Personally I have not seen this behavior before.
Since I can not double check on my own HW I am at a loss to fix this.

But somewhere in the back of my mind...

I seem to recall, that someone on Win8/10 had some sort of similar problem with a high DPI resolution monitor and windows scaling switched on. Can you test out "playing" with these settings?

**Comment by malbanGit** [comment]
PS
If worst comes to worst, it probably works if you switch off openGL support (configuration->display).
But it is slower, and looks not as nice...

**Comment by AlexandreMinard** [comment]
Switching off open gl does the trick. But, sure, it's not as nice.
I'm on MacOS, last version.

Another little issue: downloading ym files from configuration/misc does not work.
The popup says that it's okay, but it's not: ym directory remains empty.

ayfx files downloading is okay.

**Comment by malbanGit** [comment]
Hm.
I use an iMac as well - of course it is a mid2011 iMac - and I can't run the latest OS update.
(and is most probably a different/older graphics card)

YM
---
They must have changed the download page. Will check for future versions and change the link.
Thx for the hint.

**Comment by AlexandreMinard** [comment]
Thanks to you for all the answers :)
