### ISSUE TITLE
I don't understand how to draw vector list the right way

### ISSUE THREAD

**Issue by AlexandreMinard** [malbanGit/Vide#14]
Hello,

I'm trying to draw some vector lists now.
I'm working with "perfect" vectorlists like described in the documentation.

I cut my (big) picture in several little ones, then I generated the different vector lists,
but when drawing them, there is a something like a coordinate problem because the different part are not drawn where they supposed to fit.

I think I misunderstood how that works.
And, to be honest, I'm a little bit lost right now.

Here is the code used:

`	Wait_Recal();
	Intensity_a(MAX_BRIGHTNESS);          
	VIA_t1_cnt_lo = MAX_SCALE;              
	Moveto_d(0, 0);     
	VIA_t1_cnt_lo = 0x40;      
	Draw_VLc((void*)(drawing_part1)); 
	Draw_VLc((void*)(drawing_part2)); `

Thanks in advance for any help.

Regards,
Alexandre

**Comment by malbanGit** [comment]
Sorry, can’t see much from your example.

I gather you are coding in „C“.

If so following - this is a working example using 2 vectorlists:


// ***************************************************************************
// main
// ***************************************************************************
#include <vectrex.h>

const signed char Frogers_0[]=
{	+0x16,
	+0x02, -0x02, // draw to y, x
	-0x02, +0x00, // draw to y, x
	+0x01, -0x02, // draw to y, x
	+0x05, +0x03, // draw to y, x
	+0x00, -0x02, // draw to y, x
	+0x05, -0x01, // draw to y, x
	+0x00, +0x02, // draw to y, x
	-0x03, +0x00, // draw to y, x
	+0x02, +0x02, // draw to y, x
	+0x00, +0x04, // draw to y, x
	-0x02, +0x02, // draw to y, x
	+0x03, +0x00, // draw to y, x
	+0x00, +0x02, // draw to y, x
	-0x05, -0x01, // draw to y, x
	+0x00, -0x02, // draw to y, x
	-0x05, +0x03, // draw to y, x
	-0x01, -0x02, // draw to y, x
	+0x02, +0x00, // draw to y, x
	-0x02, -0x02, // draw to y, x
	+0x02, +0x00, // draw to y, x
	-0x02, -0x04, // draw to y, x
	+0x02, +0x00, // draw to y, x
	-0x02, +0x04, // draw to y, x
};
const signed char Frogers_1[]=
{	+0x16,
	-0x02, +0x02, // draw to y, x
	+0x02, +0x00, // draw to y, x
	-0x01, +0x02, // draw to y, x
	-0x05, -0x03, // draw to y, x
	+0x00, +0x02, // draw to y, x
	-0x05, +0x01, // draw to y, x
	+0x00, -0x02, // draw to y, x
	+0x03, +0x00, // draw to y, x
	-0x02, -0x02, // draw to y, x
	+0x00, -0x04, // draw to y, x
	+0x02, -0x02, // draw to y, x
	-0x03, +0x00, // draw to y, x
	+0x00, -0x02, // draw to y, x
	+0x05, +0x01, // draw to y, x
	+0x00, +0x02, // draw to y, x
	+0x05, -0x03, // draw to y, x
	+0x01, +0x02, // draw to y, x
	-0x02, +0x00, // draw to y, x
	+0x02, +0x02, // draw to y, x
	-0x02, +0x00, // draw to y, x
	+0x02, +0x04, // draw to y, x
	-0x02, +0x00, // draw to y, x
	+0x02, -0x04, // draw to y, x
};

const signed char* const Frogers[]=
{	 Frogers_0, // list of all single vectorlists in this
	 Frogers_1,
};

int main(void)
{
	int i;
	while(1)
	{
		Wait_Recal();
		VIA_t1_cnt_lo = 0x7f;
		Intensity_5F();
		for (i=0;i<2;i++)
		{
			Moveto_d(0,25+ 50*(0-i)); // x center the two lists
			Draw_VLc( (void* const)Frogers[i]);
			Reset0Ref();
		}
	};
	
	// if return value is <= 0, then a warm reset will be performed,
	// otherwise a cold reset will be performed
	return 0;
}

// ***************************************************************************
// end of file
// ***************************************************************************

**Comment by malbanGit** [comment]
Actually what might be misunderstood…

The only ABSOLUT coordinate you are ever using while drawing on Vectrex is: 0,0 and that only after a WaitRecal or a ResetRef0.
Otherwise you have to keep track of the coordinates the beam is positioned at yourself.

All moveTo or DrawXXX are relative to the point the vector hardware is currently pointing to.

Unfortunately all tutorials I did were using Assembler rather than „C“ - but the concept still hold true.
Did your read e.g. :

http://vide.malban.de/help/vectrex-tutorial-ii-starting-with-bios <http://vide.malban.de/help/vectrex-tutorial-ii-starting-with-bios>

?

**Comment by AlexandreMinard** [comment]
Thanks for the answers and the links, I'll read  quietly them!

**Comment by AlexandreMinard** [comment]
Can I send you my xml files so you can see the problem?

**Comment by malbanGit** [comment]
Sure can.

Can’t promise I will look at them today though - I’ll be on my way shortly for quite some time…

**Comment by AlexandreMinard** [comment]
thanks. please give me your email

**Comment by malbanGit** [comment]
vide AT malban DOT de

:-)

**Comment by AlexandreMinard** [comment]
Just for info, did you get my email?

**Comment by malbanGit** [comment]
Yes.

I'll look into it... Sorry - difficult to find the time right now.
(It's a "work" holiday - ... restaurating our cottage...)

Am 27.04.2020 11:04 schrieb AlexandreMinard: 

> Just for info, did you get my email? 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/malbanGit/Vide/issues/14#issuecomment-619840377
[2]

**Comment by AlexandreMinard** [comment]
Don't worry, take your time and have a nice holiday :)
