### ISSUE TITLE
Any way to trace or log something?

### ISSUE THREAD

**Issue by AlexandreMinard** [malbanGit/Vide#15]
Hello,

I'm wondering if there is any way to put traces or to have a log somewhere to debug variables?
Using the vari tool is good for sure, but I'm looking for something like a console to debug my variables.

Regards,
Alexandre

**Comment by malbanGit** [comment]
For assembler - yes.

In C I only partially implemented debugging.

You can switch 'c-debug' on in the configuration of your project and set breakpoints.

Global variables can be watched in dissi.

More in the help.
Sorry short answer - writing from my phone...


Von meinem iPhone gesendet

**Comment by AlexandreMinard** [comment]
Thanks (again) for your answer.
So you confirm that in 'C' I can't use "printf" or something similar?

**Comment by malbanGit** [comment]
Thats right, at the moment you can't.

If its important to you, I can implement something "similar" after my
holidays... but that won't help you right now.

ATM you can only "trick" "C" into thinking it is assembler.

Than you can output (as said - GLOBALs):
Example:

...
int someVar;

int main(void)
{
 someVar = 1;
asm volatile( "nop " "; hey dissi "print I am great: someVar =
$_someVar" " "nt" );
...

For further syntax on "hey dissi" - please look at the help (dissi
section)

Am 26.04.2020 22:46 schrieb AlexandreMinard: 

> Thanks (again) for your answer.
> So you confirm that in 'C' I can't use "printf" or something similar? 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/malbanGit/Vide/issues/15#issuecomment-619622466
[2]

**Comment by AlexandreMinard** [comment]
Thanks, I'll try that!

**Comment by AlexandreMinard** [comment]
So I tried and... I can't see my message :(
I didn't find it in dissi...

Here is my code, and yes targetX is a global variable, I can see it in variables window:

	asm volatile("nop" "; hey dissi " "print I am great: targetX = $_targetX" "nt" );

**Comment by malbanGit** [comment]
Hm...
In my answer the escapes around the "middle"quotes were missing...
Before the print and in your case after the _targetX the quotation marks must be escaped...

Von meinem iPhone gesendet

**Comment by AlexandreMinard** [comment]
I tried 
`	asm volatile("nop" "; hey dissi \"print I am great: targetX = $_targetX\" " "nt" );
	
	
	asm volatile( "nop " "; hey dissi \"print I am bad \" " "nt" );`

but I don't know where I'm supposed to see these logs...

**Comment by malbanGit** [comment]
Perhaps this helps:

![grafik](https://user-images.githubusercontent.com/14903082/80393827-52534800-88b1-11ea-92e9-4f5c17edf5df.png)

**Comment by malbanGit** [comment]
Sorry for these confusing short answers...

**Comment by AlexandreMinard** [comment]
Thanks for your amazing support!
It works now, I had to enable C debugging...

Is it possible to have a decimal version of the variable? Hexa is not my friend :)

**Comment by malbanGit** [comment]
No hex only at the
Moment...

But perhaps this helps...
You can write the number into the command line of dissi - it than prints the number as hecc, dec and binary.. 

A little complicated, but perhaps better than using a calculator...


Von meinem iPhone gesendet
