### ISSUE TITLE
Set working VList directory impossible?

### ISSUE THREAD

**Issue by AlexandreMinard** [malbanGit/Vide#17]
Hello,

In Vecci, in tab "vectorlist status" it looks that there is a way to set the working VList directory.
I can't make it work. I can only select a file, not a directory,
and after setting it to a file, when I open (or save) a xml vector list,
the path remains set to %VIDE%/xml/vectorlist

Is there any way to change this default folder?

Regards,
Alexandre

**Comment by malbanGit** [comment]
No, as yet there is no way to change the working directory… sorry

**Comment by AlexandreMinard** [comment]
OK no problem
