### ISSUE TITLE
YM file handling

### ISSUE THREAD

**Issue by AlexandreMinard** [malbanGit/Vide#18]
Hello,

Whatever project I load (LittleDemo, LoadRunner or even mine),
when I right click on an YM file,
the option "build Vectrex YM" is greyed out.

I tried adding a lot of different ym files, and still same result.
I even tried the "Last Ninja.ym" seen in the doc http://vectrex.malban.de/preliminary/e1fe840c.html
for the same result (yes I added in the project with the process described)

Regards,
Alexandre

**Comment by malbanGit** [comment]
Yeah…

That’s a bug I know about. In the next Vide version that is fixed.
For the time being use the YM from the Tools menu…

**Comment by AlexandreMinard** [comment]
OK Thanks
