### ISSUE TITLE
dissi  - labels shown twice

### ISSUE THREAD

**Issue by mountaingoate** [malbanGit/Vide#2]
When looking at the disassembled code, the labels show up twice, once for the real address and once earlier on another.

To reproduce:

1. Assemble a file into .BIN and .LST. I did it _outside_ Vide, it may make a difference
2. Load .BIN into **vexci** and start it. Observe the **dissi** window.
3. Labels from the .LST file are shown twice both in the Label column and also in "show labels"

Example: from .LST
`        Draw_terrain : $0282            642`
VIde shows:
'$025A	Draw_terrain'
'$0282	Draw_terrain'

**Comment by malbanGit** [comment]
What assembler are you using? I assume AS09, if so, what version? With what command line parameters are you assembling?
I did a test with AS09 Version 1.11 parameters: " -w200 -h0 -l -mcti " I have not been able to reproduce...
(Also - but unrelated - did you test assi? If you can't assemble using assi, what went wrong :-) )

**Comment by malbanGit** [comment]
Can it be, that you have BOTH a "*.cnt" and a "*.LST" file?
If so, it would still be a bug, but that would lead me perhaps in the right direction....

**Comment by mountaingoate** [comment]
Assembler is  AS09 Assembler for M6809 [1.42].
My usual options are:  -mcti -l -h0 sgj.asm
However there was a lingering .cnt file that may have caused the issue. 
Removed it, will test again.

**Comment by mountaingoate** [comment]
Didn't take long - with the old CNT file gone, labels show up perfectly once.

**Comment by malbanGit** [comment]
Ok, than I guess it was the CNT file. With the new option to only load one either CNT OR LST, this should not happen again - I close the issue...
