### ISSUE TITLE
Raster images in "C"

### ISSUE THREAD

**Issue by AlexandreMinard** [malbanGit/Vide#21]
Is there a way to use raster images in C?
Can't find that in the documentation:
http://vectrex.malban.de/preliminary/f5e2c938.html
http://vectrex.malban.de/preliminary/364f1577.html

Regards,
Alexandre

**Comment by malbanGit** [comment]
I don’t think I exported any of those function to C - so ,,, out of my head, No,

Also these functions are very timing critical - they probably cannot be written in C.
One must probably use assembler and add a library function for C access...

**Comment by AlexandreMinard** [comment]
looks complicated for me :)
thanks for your answer!
