### ISSUE TITLE
Search text

### ISSUE THREAD

**Issue by AlexandreMinard** [malbanGit/Vide#22]
Hello,

Here are 2 improvements I'd really like to have in Vide :)

- Could the search restart from the beginning of the file when end is reached?
So the "not found" message will be displayed only when the string is really not in the file, not when the string is not after the cursor?

- Could you add a shortcut to go to the next searched occurence? Like, for instance CMD + G.
So, CMD+F : Input the search text, enter to validate it.
CMD + G: go to the next one (instead of CMD+F and enter again)

Regards,
Alexandre

**Comment by malbanGit** [comment]
a) I put it on my list
b) use F3 to search again...

Am 18.05.2020 11:37 schrieb AlexandreMinard: 

> Hello, 
> 
> Here are 2 improvements I'd really like to have in Vide :) 
> 
> * 
> 
> Could the search restart from the beginning of the file when end is reached?
> So the "not found" message will be displayed only when the string is really not in the file, not when the string is not after the cursor? 
> * 
> 
> Could you add a shortcut to go to the next searched occurence? Like, for instance CMD + G.
> So, CMD+F : Input the search text, enter to validate it.
> CMD + G: go to the next one (instead of CMD+F and enter again) 
> 
> Regards,
> Alexandre 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/malbanGit/Vide/issues/22
[2]

**Comment by AlexandreMinard** [comment]
a. ok thanks
b. F3 is assigned to something else on macos, and I can't change anything in the shortcut configuration that does not work

**Comment by malbanGit** [comment]
I am working on an iMac - here it works.

There is some setting in the configs (can't look at it right now) - if
F3 is "passed" thru or not.
I took F3 because in an other IDE I used to use F3 was search (borland?)

But in the configuration you can change the key bindings "search next" /
"search previous"...

Am 18.05.2020 14:28 schrieb AlexandreMinard: 

> a. ok thanks
> b. F3 is assigned to something else on macos, and I can't change anything in the shortcut configuration that does not work 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/malbanGit/Vide/issues/22#issuecomment-630149076
[2]

**Comment by AlexandreMinard** [comment]
F3 is used to activate Mission Control on my mac, and I didn't change anything for this.

Unfortunately, changing the key bindings does not work here, even after restarting the app, event is the "search next" is assigned to CMD G.

**Comment by malbanGit** [comment]
I'll have to check that on my mac.

Am 18.05.2020 15:07 schrieb AlexandreMinard: 

> F3 is used to activate Mission Control on my mac, and I didn't change anything for this. 
> 
> Unfortunately, changing the key bindings does not work here, even after restarting the app, event is the "search next" is assigned to CMD G. 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1] https://github.com/malbanGit/Vide/issues/22#issuecomment-630170476
[2]

**Comment by malbanGit** [comment]
I don't know how often you use Mac OS shortcuts - personally I NEVER use them.

If you don't either - you can check this checkbox - and F3 will work!

![grafik](https://user-images.githubusercontent.com/14903082/82355774-f9378980-9a02-11ea-9c3d-eaf31db84a42.png)

**Comment by malbanGit** [comment]
BTW
I tried assigning (for "fun") META +B as my next search key.
That works - although for the settings to take effect I had to close and open the editor.

**Comment by AlexandreMinard** [comment]
thanks, it finally works to change the shortcut
don't know why it does not work yesterday... my mistake for sure!!!

**Comment by AlexandreMinard** [comment]
reopened for the 1st point :)
