### ISSUE TITLE
Generating .exe for Windows

### ISSUE THREAD

**Issue by jameshball** [malbanGit/Vide#31]
Hi,

First of all, thanks for creating a great IDE!

I'm currently looking to add a small feature, and have opened the project in NetBeans just fine, but couldn't find any build target that generates the Vide.app folder with Vide.exe etc. Presumably, this is using `jlink` but it would be nice to replicate the way you have built this.

Also related, when building the project and launching the .jar, I have a Windows-XP style GUI with blurry images and a distorted emulator:

![image](https://user-images.githubusercontent.com/38670946/131122998-8e171d38-6b78-42a8-977a-e6ce3fd377e7.png)

Running from the pre-compiled .exe or .bat file you provided looks fine:

![image](https://user-images.githubusercontent.com/38670946/131123215-3e76fe87-5c01-4928-878c-02356c4cee4f.png)

I was wondering whether you knew why this was happening and what I could do to prevent it.

Thanks!
James.

**Comment by malbanGit** [comment]
I admit I never did a code merge with GitHub - I followed the online instructions - and it seems it merged correctly :-).

I am on holidays for a couple of days - so I cannot test anything correctly yet - or setup a new distribution.
I will do so soon, when I get home again (about 1 1/2 weeks) from now.

Thanks for your support and addition to Vide!

**Comment by jameshball** [comment]
Yep thanks it looks like you've merged it correctly!

No rush with the new distribution :) Just for future reference I would suggest you test the changes in a merge request locally before merging (by cloning their forked repo) to prevent merging changes that might accidentally break anything - that being said I've tried to test it as much as I can!

Git is super useful for general development too as well as just sharing your source code - serves as a very nice way to backup all the changes you've made over time and work out what new code causes an issue. I don't know how much Git you know but I'd really recommend learning the basics if you're new to it so you can use it whenever you need to add a small feature :)

Anyway, thanks again for merging and for Vide!

**Comment by malbanGit** [comment]
I think this is resolved?
