### ISSUE TITLE
Vecci SmartList "Play" button stops working

### ISSUE THREAD

**Issue by phillipeaton** [malbanGit/Vide#34]
When using Vecci for SmartList design, sometime when I hit the Play button, next to the Runnable check box, _nothing happens_.

This is usually when I'm changing Scale, Default Factor or toggling between Old Smart List and Vb Smart List and then Build List, but not actually changing any vectors in the editor. 

Once _nothing happens_, I have to keep pressing buttons and changing values and, after a few attempts, Play will again work.

**Comment by phillipeaton** [comment]
With my current simple test vector, if I enter a scale of $66, the Play button works. If I enter $67, it doesn't. 

![image](https://user-images.githubusercontent.com/44277038/139744426-ad2d3d4d-2817-41ad-bd51-ca7fc1806a66.png)

I think I worked out why...the assembly fails...

![image](https://user-images.githubusercontent.com/44277038/139744924-17eac222-b2eb-4396-b753-b71365b9b962.png)

I looked at the help text, it does sort of warn you that you are somewhat "In the Land of Mordor where the shadows lie", but knowing you should check the Debug window in the event of a problem might be of help 🙂

**Comment by malbanGit** [comment]
Yes this can be the case. 
2 points on that.
a) if that happens, open the „runnable“ source in the editor and run it there - it will output the error message
b) the smartlist functionnames, that are generated are exactly that GENERATED - there are more possible permutations of smartlist function names, that can be generated than actually are available in the template.
If one of the generated functions are missing you must create it - usually this requires a copy and paste and changing some minor stuff…

But you are right, this is not documented - and you are the first one besides myself who ever noticed…

Von meinem iPhone gesendet

**Comment by phillipeaton** [comment]
Thanks for the response, I'm not finding the missing permutations yet, all my sprites are simple so far.
