### ISSUE TITLE
Vecci SmartList Smart List generators not using optimal address mode

### ISSUE THREAD

**Issue by phillipeaton** [malbanGit/Vide#35]
In the Vecci SmartList Old Smart List generator, should `STA VIA_cntl` and `stB VIA_t1_cnt_lo`, be Direct mode i.e. have a `<` before the equ?
```
SM_lastDraw_rts2                                          ;#isfunction
                    ldb      gameScale
                    lda      #$f0
                    stB      VIA_t1_cnt_lo
                    sta      <VIA_shift_reg
SM_rts2:                                                  ;#isfunction
                    LDa      #$CC
                    STA      VIA_cntl                     ;/BLANK low and /ZERO low
```
There are a few like this in the Vb Smart List template also, I think I alos saw some instuctions forcing Extended mode.

Every saved cycle counts! 🙂

**Comment by malbanGit** [comment]
You are right.

Thing is the assembler in vide is smart enough to recognize this and optimzes extended addressing to direct.
I never thought anyone would translate the source to a forth assembler :-)…

Von meinem iPhone gesendet

**Comment by malbanGit** [comment]
You should NOT change it, when I forced extended addressing - this most probably is timing related - and some vectrex need those extra cycles!

Von meinem iPhone gesendet

**Comment by phillipeaton** [comment]
Would it be better to use Direct mode and add a NOP for clarity? (Especially if the assembler is going to optimise to Direct when you're not looking!)

**Comment by malbanGit** [comment]
A NOP is two cycles, the difference between direct and extended is one cycle.

I remember someone saying EVERY cycle counts! :-)

**Comment by phillipeaton** [comment]
Ah, I assumed NOP was one cycle, you learn something new every day. Maybe good to document that in the code somewhere close to stop newbie's like me wondering! (Maybe you already did and I didn't see it.)
Thanks for the reply 👍
