### ISSUE TITLE
vecxi Simulator window too small

### ISSUE THREAD

**Issue by captnhanky** [malbanGit/Vide#37]
<img width="1440" alt="Bildschirmfoto 2022-04-26 um 03 07 30" src="https://user-images.githubusercontent.com/47078515/165199580-591d2ac3-e6c5-4ecb-b791-dea8cc4017a6.png">

Hi!

The vecxi simulator window with openGL is too small ..it is only visible in the top left corner..1/4 of the predetermined size..I can not find anything to change this. 
..see attachment.
The old version (without openGL) works normally
(I tried version 2.5, 2.51 and 3.0 n my 2013 macbook pro running big sur 11.3.)

some minor things I noticed:
..on the screenshot you see that the bottom of the configuration menu is not visible

..in version 3.0 it in help- about says version 2.5 and in the mac menu on top left- about section vide- vide main is 1.0 (don´t know if this is the current version)

cheers 
Andy

**Comment by malbanGit** [comment]
Have you tried the new RC version, I believe the OpenGL version should be fixed…
(V2.6 RC3)

Von meinem iPhone gesendet
