### ISSUE TITLE
Vecxi bin file edit box shows all game keyboard input

### ISSUE THREAD

**Issue by mountaingoate** [malbanGit/Vide#6]
When a game is started in Vecxi, all keyboard input to the actual game is shown in the "Bin File" input box.

 It would be good if that box only had focus after it was actually clicked.

**Comment by malbanGit** [comment]
Hehe,
you don't how often I was bothered by that focus on the input box, don't know why I haven't fixed that long ago...

...will do... soon...

Regards

Malban

**Comment by mountaingoate** [comment]
Sounds great, thank you.

**Comment by malbanGit** [comment]
As a "quick" fix, I simply do not allow the TextEdit to have a focus at all.
I guess nobody really typed in a filename anyway, there IS after all a FileChoser.

Anyways, the chosing and loading of bin files will move away from the Vecx-panel anyway at some stage, so I didn't put to much effort into a "real" fix.
