### ISSUE TITLE
can't get to the bottom of some windows

### ISSUE THREAD

**Issue by vtk-vectrex** [malbanGit/Vide#7]
hey Malban  :)

i installed Vide V1.06 and have begun to have an initial look around and get used to it

i am using windows 7 (64bit), running on a laptop which uses a screen allowing maximum resolution of 1366 x **768**

the problem i am having is, when i went into the Vide configuration, for some of the tabs (Emulator, Delays, Keyboard, Input) - i cannot get to the very bottom to see/change any options down there (there is no side scroll bar present.. except for on the 'Keyboard' tab, but even so  that scroll bar does not let me go down far enough to see the options at the bottom either)

i have attached some screenshots here so you can see the issue...

(perhaps you could set your desktop to 768 lines height (or less), to see if you also get the problem?)

thanks!

![pic1](https://cloud.githubusercontent.com/assets/23404506/20222101/f10df23e-a82b-11e6-9c7d-1efba0b5e3fc.png)

![pic2](https://cloud.githubusercontent.com/assets/23404506/20222102/f110db8e-a82b-11e6-9ed0-939c486dcf54.png)

![pic3](https://cloud.githubusercontent.com/assets/23404506/20222103/f1122fde-a82b-11e6-83a0-c1d2b7a3a99e.png)

![pic4](https://cloud.githubusercontent.com/assets/23404506/20222104/f11445c6-a82b-11e6-9cbe-ed2d500313b9.png)

**Comment by malbanGit** [comment]
Yes - I see what you mean.
No need for further examples :-).

I see what I can do - I'll comment progress via this bug. Over the weekend I'll have my nice visiting so I won't be able to do anything "useful" (since the guest room is also the room my Mac resides).

**Comment by malbanGit** [comment]
Ok,
It wasn't a big deal - fixed it, the configuration is now scrollable. In Vide 1.07 it will be included - but it isn't uploaded yet. For this I must wait a few days.
Regards
Malban

**Comment by vtk-vectrex** [comment]
hey, thanks and hope u have a nice weekend :)

**Comment by JeffB42** [comment]
Was this ever fixed (and released)?  I'm running ver 2.6 RC3 on a mac and I'm running into the same issue.
