### ISSUE TITLE
label Navigator not showing macro labels

### ISSUE THREAD

**Issue by gauze** [malbanGit/Vide#8]
I don't know if this is just an unfinished feature ...

**Comment by malbanGit** [comment]
Please elaborate:
![grafik](https://cloud.githubusercontent.com/assets/14903082/25145759/25f05e48-2472-11e7-8b00-412f14809548.png)

**Comment by gauze** [comment]
v 1.13 isn't showing them

![videbuigss](https://cloud.githubusercontent.com/assets/116427/25149652/3aa89a6e-244d-11e7-970a-49d801fd35b7.png)

**Comment by malbanGit** [comment]
Ah...

The label that is visible in the screenshot is not a macro label per se - since it is a global label.
You should either end it with \? or declare it as local after the header of the macro.

If you use THAT macro several times, the label "bstart" gets redefined every time the macro is used. Which might lead to erratic behaviour.

Nonetheless - I check if something is wrong. I am not sure if the keyword local correctly identifies macro labels - now that you mention it.

**Comment by gauze** [comment]
hm I am not sure what you mean by declare it local in the terms of assembly stuff ... also I added \? to end of that macroname and it throws an error can you give a proper macro example with this?!

****** bad label
       projects\Turmoil\macros.i(1436): DRAW_BULLETS\?        macro   

and yes in macros I use more than once I have the "local var1,var2,etc" parameter so the internal labels work right, because I noticed this erratic behavior ;)

**Comment by malbanGit** [comment]
"\\?" not "?"
![grafik](https://cloud.githubusercontent.com/assets/14903082/25152835/aac74254-248a-11e7-8767-cbbccad5fb3b.png)

**Comment by gauze** [comment]
oh I don't use those anywhere. (I use this version instead:
example:

DRAW_VLC            macro    
                    local    LF3F4,Draw_VLa 
                    lda      ,x+ 
Draw_VLa 
                    sta      $C823 
                    ldd      ,x 
                    sta      <VIA_port_a                  ;Send Y to A/D 
                    clr      <VIA_port_b                  ;Enable mux 
                    leax     2,x                          ;Point to next coordinate pair 
                    nop                                   ;Wait a moment 
                    inc      <VIA_port_b                  ;Disable mux 
                    stb      <VIA_port_a                  ;Send X to A/D 
                    ldd      #$FF00                       ;Shift reg=$FF (solid line), T1H=0 
                    sta      <VIA_shift_reg               ;Put pattern in shift register 
                    stb      <VIA_t1_cnt_hi               ;Set T1H (scale factor?) 
                    ldd      #$0040                       ;B-reg = T1 interrupt bit 
LF3F4:              bitb     <VIA_int_flags               ;Wait for T1 to time out 
                    beq      LF3F4 
                    nop                                   ;Wait a moment more 
                    sta      <VIA_shift_reg               ;Clear shift register (blank output) 
                    lda      $C823                        ;Decrement line count 
                    deca     
                    bpl      Draw_VLa                     ;Go back for more points 
                                                          ; jmp Check0Ref ;Reset zero reference if necessary 
                    endm  


and it's not what I was asking about, so "macro labels" doesn't refer to the NAMES of macros then? I was looking for "DRAW_BULLETS" in the list which is the macro's name.

**Comment by malbanGit** [comment]
Ok.
Nah - haven't done that... But I put it on my todo list :-).

When I've done it - I'll close the ticket and you'll be notified.
Its not a big thing todo...

Malban

**Comment by gauze** [comment]
excellent, thanks.

**Comment by malbanGit** [comment]
Just implemented the new label type "macro definition" and the ability to list them.
In Vide V1.14 it will be available.
